<?php
/**
 * @file
 *
 */

/* ====================== */
/* ==== BACKDROP HOOKS ==== */
/* ====================== */

/**
 * Implements hook_menu().
 *
 * @return
 *   An array of menu items.
 */
function waypoints_menu() {
  $items = array();

  $items['admin/config/user-interface/waypoints'] = array(
    'title' => 'jQuery Waypoints',
    'description' => 'Configure Waypoints module.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('waypoints_settings_form'),
    'access arguments' => array('configure waypoints module'),
    'file' => 'includes/waypoints.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 *
 * @return array
 *   An array of valid permissions for the browserclass module
 */
function waypoints_permission() {
  return array(
    'configure waypoints module' => array(
      'title' => 'Configure jQuery Waypoints module',
      'description' => 'Configure jQuery Waypoints module, set JavaScript operation.',
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function waypoints_config_info() {
  $prefixes['waypoints.settings'] = array(
    'label' => t('Module name settings'),
    'group' => t('Configuration'),
  );
}

/**
 * Implements hook_init().
 */
function waypoints_init() {
  if (config_get('waypoints.settings', 'waypoints_always_add_js')) {
    backdrop_add_library('waypoints', 'waypoints', TRUE);
  } 
}

/**
 * Implements hook_library_info().
 *
 * @return array
 *   An array defining libraries associated with a module.
 */
function waypoints_library_info() {
  $libraries = array();

  $libraries['waypoints'] = array(
    'title' => 'jQuery Waypoints',
    'website' => 'http://imakewebthings.github.com/jquery-waypoints/',
    'version' => '4.0.1',
    'js' => array(
      backdrop_get_path('module', 'waypoints') . '/library/jquery.waypoints.min.js' => array(),
    ),
  );

  return $libraries;
}
