<?php
/**
 * @file
 *
 *
 *
 * @author Kálmán Hosszu - hosszu.kalman@gmail.com - http://www.kalman-hosszu.com
 */

/**
* Implements hook_config_info().
*/
function waypoints_config_info() {
  $prefixes['waypoints.settings'] = array(
    'label' => t('Main settings'),
    'group' => t('Waypoints'),
  );
  return $prefixes;
}

/**
 * Implement of hook_menu().
 *
 * @return
 *   An array of menu items.
 */
function waypoints_menu() {
  $items = array();

  $items['admin/config/development/waypoints'] = array(
    'title' => 'jQuery Waypoints',
    'description' => 'Configure Waypoints module.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('waypoints_settings_form'),
    'access arguments' => array('configure waypoints module'),
    'file' => 'includes/waypoints.admin.inc',
  );

  return $items;
}

/**
 * Implement of hook_permission().
 *
 * @return array
 *   An array of valid permissions for the browserclass module
 */
function waypoints_permission() {
  return array(
    'configure waypoints module' => array(
      'title' => 'Configure jQuery Waypoints module',
      'description' => 'Configure jQuery Waypoints module, set JavaScript operation.',
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implement of hook_init().
 */
function waypoints_init() {
  if (config_get('waypoints.settings', 'always_add_js')) {
    backdrop_add_js(backdrop_get_path('module', 'waypoints') . '/js/waypoints.min.js');
  }
}